name: untitled8
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  flutter_screenutil: ^5.9.3
  flutter_slidable: ^3.1.1
  uuid: ^3.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  font_awesome_flutter: ^10.0.0
  lottie: ^3.1.2
  datetime_picker_formfield_new: ^2.1.0

min_sdk_android: 21
flutter:
  uses-material-design: true
  assets:
    - lib/assets/lottie/devices.json

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner:
  flutter_lints: ^4.0.0
